server: Server {
    auth_scheme: Auth Scheme
    forwarder: Forwarder {
      rate-limiter: Rate Limiter
      least-conn: Least Connection
      rate-limiter -> least-conn
    }
    auth_scheme -> forwarder.rate-limiter
  }
  upstream1: Upstream 1
  upstream2: Upstream 2
  user: User {shape: person}
  user -> server.auth_scheme: mTLS
  server.forwarder.least-conn -> upstream1
  server.forwarder.least-conn -> upstream2
  